version: "2"
services:
  db:
    container_name: db_mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    expose:
      - "27017"
  ontouml-server:
    container_name: ontouml-server
    build: .
    restart: always
    ports:
      - "50051:50051"
    links:
      - db
